baseURL: "/"
languageCode: "en-us"
theme: "hugo-theme-novela"
title: "Hugo Novela"
pygmentsstyle: "monokai"
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: Law
