baseURL: "/"
languageCode: "en-us"
theme: "hugo-theme-novela"
title: "Pilipinas.pages.dev"
pygmentsstyle: "monokai"
paginate: 6
social:
  twitter: "https://twitter.com/law_aritao"
  github: "https://github.com/lawrenceaph"
  instagram: "https://instagram.com/coffeeandthis"
  # linkedin: "#"
  # dribbble: "#"
  # youtube: "#"
taxonomies:
  author: Law
